# Generated by Django 2.2.5 on 2019-09-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomodel',
            name='f_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
